apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: word-app-service
  labels:
    app: word-app-service
spec:
  type: NodePort
  ports:
  - port: 3000
    name: word-app-service
    targetPort: 3000
  selector:
    app: word-app-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-app-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-app-service
  template:
    metadata:
      labels:
        app: word-app-service
    spec:
      containers:
      - name: word-app-service-container
        image: word-app-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: WORDS
            valueFrom:
              configMapKeyRef:
                name: word-app-config
                key: words
        