apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./backend
  - ./frontend
  - namespace.yaml

namespace: word-app

configMapGenerator:
  - name: word-app-config
    literals:
      - "words=nicht,schlecht,oder"

secretGenerator:
  - name: word-app-secret