apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./backend
  - ./frontend
  - namespace.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

configMapGenerator:
  - name: word-app-config
    namespace: word-app
    literals:
      - "words=nicht,schlecht,oder"

secretGenerator:
  - name: word-app-secret
    namespace: word-app