apiVersion: v1
kind: Service
metadata:
  name: word-app-frontend
spec:
  selector:
    app: word-app-frontend
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32757
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-app-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-app-frontend
  template:
    metadata:
      labels:
        app: word-app-frontend
    spec:
      containers:
      - name: word-app-frontend-container
        image: word-app-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: WELCOME_MESSAGE
            valueFrom:
              secretKeyRef:
                name: word-app-secret
                key: welcome_message
