apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

secretGenerator:
  - name: word-app-secret
    namespace: word-app
    behavior: replace
    literals:
      - "welcome_message=Welcome, here is your random word:"